### ISSUE TITLE
Getting 'System.InvalidOperationException: Current error context error is different to requested error' when adding an item

### ISSUE THREAD

**Issue by derekantrican** [ceee/PocketSharp#44]
I'm getting an exception thrown when calling `PocketClient.Add`. _The item DOES get added to Pocket, but the exception is thrown._ I tried de-authorizing the PocketClient & re-authorizing but I'm still getting the exception.

The stack trace and [this SO post](https://stackoverflow.com/questions/34396039/current-error-context-error-is-different-to-requested-error-exception-in-json) seem to imply it's something about Newtonsoft trying to get the error context within a JsonConverter called by another JsonConverter.

Code:

```csharp
try
{
    string youTubeURL = Common.YOUTUBEVIDEOBASEURL + youTubeVideoId;
    await Settings.PocketClient.Add(new Uri(youTubeURL));
}
catch (Exception ex)
{
    Log("Exception thrown when adding to pocket!");
    Common.DumpException(ex);
}
```

Full exception details:

```
Current error context error is different to requested error.

    at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.GetErrorContext(Object currentObject, Object member, String path, Exception error)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.IsErrorHandled(Object currentObject, JsonContract contract, Object keyValue, IJsonLineInfo lineInfo, String path, Exception ex)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PocketSharp.PocketClient.DeserializeJson[T](String json)
   at PocketSharp.PocketClient.<Request>d__79`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PocketSharp.PocketClient.<Add>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyApp.Main.<AddYouTubeVideoToPocket>d__15.MoveNext()
```

**Comment by derekantrican** [comment]
Downloaded the PocketSharp code and included it in my project to do deeper debugging. The true exception is being thrown in one of the converters due to a null value. For some reason, it seems the json being received in the response is quite sparse:

```json
{
	"item": {
		"item_id": "3457258454",
		"normal_url": "http:\/\/youtube.com\/watch?v=kOdnMGLy5aM",
		"resolved_id": "0",
		"extended_item_id": null,
		"resolved_url": null,
		"domain_id": null,
		"origin_domain_id": null,
		"response_code": null,
		"mime_type": null,
		"content_length": null,
		"encoding": null,
		"date_resolved": null,
		"date_published": null,
		"title": null,
		"excerpt": null,
		"word_count": null,
		"innerdomain_redirect": null,
		"login_required": null,
		"has_image": null,
		"has_video": null,
		"is_index": null,
		"is_article": null,
		"used_fallback": null,
		"lang": null,
		"time_first_parsed": null,
		"given_url": "https:\/\/www.youtube.com\/watch?v=kOdnMGLy5aM"
	},
	"status": 1
}
```

**Comment by derekantrican** [comment]
Closing as this seems to be specific to one computer so not a problem with the library (other computer is getting full json responses - example below). Though I'm still bewildered at what could be causing this.

```json
{
	"item": {
		"item_id": "3457434860",
		"normal_url": "http:\/\/youtube.com\/watch?v=nfwSKs3P-tM",
		"resolved_id": "3457434860",
		"extended_item_id": "3457434860",
		"resolved_url": "https:\/\/www.youtube.com\/watch?v=nfwSKs3P-tM",
		"domain_id": "856",
		"origin_domain_id": "856",
		"response_code": "200",
		"mime_type": "",
		"content_length": "0",
		"encoding": "",
		"date_resolved": "2021-10-15 17:00:31",
		"date_published": "2021-10-15 17:00:18",
		"title": "How Many Glass Windows Stops A Throwing Axe???",
		"excerpt": "Thanks to Bespoke Post for sponsoring - Get 20% off your first monthly box when you sign up at https:\/\/bspk.me\/ridiculous20 and use promo code REXY20 at checkout!\n\nBUY HR MERCH \u27a4 https:\/\/bit.ly\/HRMerchStore\n\nSUBSCRIBE \u27a4 http:\/\/bit.ly\/SubHowRidiculous\n\nBECOME A MEMBER \u27a4 and get exclusive perks",
		"word_count": "0",
		"innerdomain_redirect": "1",
		"login_required": "0",
		"has_image": "1",
		"has_video": "2",
		"is_index": "0",
		"is_article": "0",
		"used_fallback": "0",
		"lang": "en",
		"time_first_parsed": "1634335231",
		"authors": {
			"34920032": {
				"author_id": "34920032",
				"name": "How Ridiculous",
				"url": "https:\/\/www.youtube.com\/channel\/UC5f5IV0Bf79YLp_p9nfInRA"
			}
		},
		"images": {
			"1": {
				"item_id": "3457434860",
				"image_id": "1",
				"src": "https:\/\/i.ytimg.com\/vi\/nfwSKs3P-tM\/maxresdefault.jpg",
				"width": "1280",
				"height": "720",
				"credit": "",
				"caption": ""
			}
		},
		"videos": {
			"1": {
				"item_id": "3457434860",
				"video_id": "1",
				"src": "http:\/\/www.youtube.com\/watch?v=nfwSKs3P-tM",
				"width": "0",
				"height": "0",
				"type": "1",
				"vid": "nfwSKs3P-tM",
				"length": "1074"
			}
		},
		"resolved_normal_url": "http:\/\/youtube.com\/watch?v=nfwSKs3P-tM",
		"domain_metadata": {
			"name": "YouTube",
			"logo": "https:\/\/logo.clearbit.com\/youtube.com?size=800",
			"greyscale_logo": "https:\/\/logo.clearbit.com\/youtube.com?size=800&greyscale=true"
		},
		"given_url": "https:\/\/www.youtube.com\/watch?v=nfwSKs3P-tM"
	},
	"status": 1
}
```

**Comment by derekantrican** [comment]
I have, however, found that the original error ("Current error context is different to requested error") is due to throwing an exception inside the error handler:

https://github.com/ceee/PocketSharp/blob/0209d1a5b13e97ba8f4be0cae8a6328daf53d173/PocketSharp/PocketClient.cs#L357-L360

So perhaps this should be done differently as it doesn't return the error properly to the consumer of the library.
